### ISSUE TITLE
Not able to use this card from auto-entities 

### ISSUE THREAD

**Issue by TSM-Evo2** [custom-cards/secondaryinfo-entity-row#10]
https://github.com/thomasloven/lovelace-auto-entities

This card doesn't seem to work when used in conjuction with the auto entities card.

**Comment by MizterB** [comment]
This was fixed in version 0.3:

_The configured entity object can now be referenced as {entity} inside a template. This enables compatibility with dynamic entity list generators such as auto-entities._
