### ISSUE TITLE
Using weblink in secondary info

### ISSUE THREAD

**Issue by jchasey** [custom-cards/secondaryinfo-entity-row#11]
It would be great to be able to reference a weblink entity and therefore create a link off of that in the secondary info area.

e.g:
```
- entity: sensor.next7days_farmhouse
  icon: mdi:hotel
  name: 'Farmhouse'
  type: custom:secondaryinfo-entity-row
  secondary_info: "[[ weblink.bookings_farmhouse ]]"
```

**Comment by MizterB** [comment]
I haven't tried this myself, but have you considered making the secondary_info value something like:

`secondary_info: "<a href='[[ weblink.bookings_farmhouse ]]'>[[ weblink.bookings_farmhouse ]]</href>"`

**Comment by jchasey** [comment]
I ended up using the custom-weblink lovelace card as a solution, but just tried your suggestion and that works too - thanks
