### ISSUE TITLE
Config is not supported by the UI editor

### ISSUE THREAD

**Issue by emilicus** [custom-cards/secondaryinfo-entity-row#14]
Hello i'm on hass.io  0.95.4 configured with HACS and this plugin.
While configuring some basic entities cards, i'm getting this error in the card setup window:

Your config is not supported by the UI editor:
Expected a value of type `{entity,name,icon} | entity-id` for `entities.0.secondary_info` but received `"[[ sun.sun.last_changed ]]"`.
Falling back to YAML editor. 

Also, even if the secondary infos are displayed, the GUI becomes very sluggish until i comment the secondary-info section.

Please don't take in account for the secondary-info attributes actually used: it is only a testing one, just to give the idea ;-)

Attached the configs i'm using

Any hints?

TIA

<img width="748" alt="en9tities_yaml" src="https://user-images.githubusercontent.com/52722035/61353979-5b6aaf80-a871-11e9-8f8c-9e66e6b84dfe.png">
[lovelaceUI_yaml.txt](https://github.com/custom-cards/secondaryinfo-entity-row/files/3400545/lovelaceUI_yaml.txt)
[card.txt](https://github.com/custom-cards/secondaryinfo-entity-row/files/3400546/card.txt)

**Comment by emilicus** [comment]
Hello all - anyone on this?
TIA ;-)

**Comment by MizterB** [comment]
Not sure how to help here...I don't believe the UI editor is intended to support custom cards like this.  It will allow you provide the right information and might provide some basic preview capabilities, but the validation is always going to fail.  Behavior for me is erratic, but the best way to be using this card is to manually update the Lovelace config files.

**Comment by iantrich** [comment]
That is not really an error, just a fact. The UI editor does not support those fields, so it takes you to the YAML editor
