### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by Vendo232** [custom-cards/secondaryinfo-entity-row#17]
Hi

I`m getting error when trying to pull battery level on Wyze binary sensor using this script.

Can you spont an error? 
![Capt233232ure](https://user-images.githubusercontent.com/44098230/63884098-ce983300-c992-11e9-8279-c304f36ba14e.PNG)

entities:
  - entity: binary_sensor.wyzesense_778bb687
    name: Front Door
    secondary_info: '[[ binary_sensor.wyzesense_778bb687.battery_level ]]'
    type: 'custom:secondaryinfo-entity-row'
title: Wyze Battery
type: entities

**Comment by MizterB** [comment]
I'm assuming that battery_level is an attribute of your sensor?  If so, you should be using:

`secondary_info: '[[ binary_sensor.wyzesense_778bb687.attributes.battery_level ]]'`

**Comment by Vendo232** [comment]
it worked! thank you Sir!
