### ISSUE TITLE
reference {entity} inside conditional? 

### ISSUE THREAD

**Issue by JonGilmore** [custom-cards/secondaryinfo-entity-row#20]
It appears we're not able to reference `{entity}` inside of a conditional. Would we be able to enhance this card to support this?  For example, this doesn't work:

```
secondary_info: '[[ if({entity}.attributes.years_at_next_anniversary == "undefined", "", {entity}.attributes.years_at_next_anniversary) ]]'
```

**Comment by majkers** [comment]
Same for me and I neeed it very badly. Could You please fix it?

**Comment by Berserkir-Wolf** [comment]
+1 for this as well. Just throws `missed comma between flow collection entries`.

**Comment by ed-holland** [comment]
+1 from my side also. It would become more consistent.

**Comment by JonGilmore** [comment]
For the people that are following this issue, I ended up ditching this card and opting for `lovelace-template-entity-row` instead. [This ended up being](https://github.com/thomasloven/lovelace-template-entity-row/issues/32#issuecomment-679270026) a better solution for me.
