### ISSUE TITLE
Problem with HA 0.105.0b0

### ISSUE THREAD

**Issue by bussio** [custom-cards/secondaryinfo-entity-row#22]
Since the latest beta (0.105.0b0) from HA, the issue of this card has not worked.
- type entities
  title: WZ
  entities:
    - entity: switch.shelly_shplg_s_040f0f
       name: Shelly Plug S socket WZ outside
       type: "custom: secondaryinfo-entity-row"
       secondary_info: "192.168.178.69"

results in the following error message:

Unknown type encountered: custom:secondaryinfo-entity-row

entity: switch.shelly_shplg_s_040f0f
name: Shelly Plug S socket WZ outside
type: "custom: secondaryinfo-entity-row"
secondary_info: "192.168.178.69"

**Comment by niemyjski** [comment]
I'm seeing this since this morning with 104.x and all I did was update card-tools, and maybe some other custom components.

**Comment by bussio** [comment]
> ... was update card-tools, and maybe some other custom components.

thanks, but unfortunately it wasn't.

**Comment by soloam** [comment]
I think that the new card-tools is braking this plugin!

**Comment by DavidFW1960** [comment]
I agree re card tools breaking it
I am seeing:
![image](https://user-images.githubusercontent.com/36390762/73509354-f5bbca80-4432-11ea-9acf-909c7fd4145d.png)

**Comment by Petro31** [comment]
Yep, updated card tools, and its now broken.

**Comment by Petro31** [comment]
Just reverted card tools and all is good again.  Super simple with HACS

**Comment by soloam** [comment]
Yes, I did that too, but hope that some uprated is submitted to this plug-in! Card-Tools is a plug-in that should be updated

**Comment by bladeback** [comment]
Hello, how do I downgrade to a previous functional release?

**Comment by bladeback** [comment]
> Prostě vrácené kartové nástroje a vše je zase dobré. Super jednoduché s HACS

Hello, how do I downgrade to a previous functional release?

**Comment by MizterB** [comment]
@thomasloven - Thank you for the PR.  It has been merged and the custom card has been updated and verified as working with the latest card tools.
