### ISSUE TITLE
HACS installation instructions wrong?

### ISSUE THREAD

**Issue by krasatos** [custom-cards/secondaryinfo-entity-row#25]
Documentation says to install as `type: null`, had to install as `type: module` to get it to work.
Didn't know how to let you know :)

**Comment by MizterB** [comment]
@iantrich I'm not sure how those instructions get auto-generated in HACS.  Is there something I need to add to the repo to specify the import type?

**Comment by iantrich** [comment]
The readme is parsed. I updated the readme for you: https://github.com/custom-cards/secondaryinfo-entity-row/blob/master/README.md#2-install-secondary-info-entity-row

**Comment by MizterB** [comment]
Thank you!
