### ISSUE TITLE
Refresh page > "Unknown type encountered"-error

### ISSUE THREAD

**Issue by exetico** [custom-cards/secondaryinfo-entity-row#27]
Hi,

I'm on the latest version of HA, and most of the times where i'm using the "Refresh" option in Lovelave, the `secondaryinfo-entity-row`-entities is returning `Unknown type encountered: toggle`-errors.

It also showing up from time to time, if the app is just reloading the page, and so. And it's here, i found it to be the biggest problem, cause my girlfriend are complaining about it, too :-D

```
Unknown type encountered: toggle.

entity: switch.sonoff4
type: toggle
secondary_info: 'Lyd fra [[ if(switch.nodemcu4678858 == on, "Chromecast Audio", "Stationær") ]]'

Unknown type encountered: text.

entity: binary_sensor.0x00158d0001d672e5_occupancy
name: Bevægelse
icon: 'mdi:run'
type: text
secondary_info: 'Stationær er [[ if(sensor.stationaer == "Online", "tændt", "slukket") ]]'

```

![image](https://user-images.githubusercontent.com/3549445/75435947-11dc5a00-5954-11ea-8b36-ed9abe4f5602.png)

The secondaryinto-entity-row is within an **vertical-stack** with multiple cards.

And it's reporting the following, in my console:
```
TypeError: e.parentElement is nullhui-stack-card.ts:97:4
    _rebuildCard hui-stack-card.ts:97
    _createCardElement hui-stack-card.ts:85
    r fire_event.ts:76
    a create-element-base.ts:92
```

If i use the tree dots, and update my lovelave-interface again, the errors are gone:
![image](https://user-images.githubusercontent.com/3549445/75436437-d8581e80-5954-11ea-9591-9b636739f105.png)

If it do it again, there's a big change, for the errors to show up, agian.

So i'm not sure if this is related to some tmp-values, a timing issue, some caching related, or... well... something else :( :)

**Comment by spudje** [comment]
Same here, Latest HA breaks secondaryinfo-entity-row

**Comment by snakuzzo** [comment]
Same here with covers...

I expect this:
![image](https://user-images.githubusercontent.com/7205371/77047361-e550b680-69c4-11ea-8060-f262c73b5948.png)

...bute this is showed...

![image](https://user-images.githubusercontent.com/7205371/77047412-f8638680-69c4-11ea-883c-857bff374bf7.png)

**Comment by gerardo15** [comment]
Im also experiencing this in the latest Home assistant release.

**Comment by snakuzzo** [comment]
For now, waiting for the fix, I'm using this...

https://github.com/gadgetchnnel/lovelace-card-preloader

**Comment by MichaelThomasMPT** [comment]
I'm also experiencing this after updating to version 0.107

**Comment by exetico** [comment]
I would like to have this fixed, however, i don't like the "preloader-fix". Maybe i should look for another card, if this is not fixed, in a short period of time :-) 

@MizterB - Are you able to see what's going on, and if you can this it :-)?

**Comment by snakuzzo** [comment]
On my HA preloader-fix sometimes doesn't work ... and I don't know why

**Comment by exetico** [comment]
I've not updated HA in the last couple of week. Has anyone, found a fix for this? :-)

**Comment by exetico** [comment]
Maybe, we should just move to:
https://github.com/thomasloven/lovelace-template-entity-row

Or? I'm not that sure..
